### ISSUE TITLE
Unable to sign up when locally running the repo

### ISSUE THREAD

**Issue by Ashu3208** [divc13/Unified-Portal-For-Hall-Automation#10]
![image](https://user-images.githubusercontent.com/92543518/230584271-6d7c3280-b936-44dd-a79e-927f3aea596b.png)
On the local machine, no longer able to register as any type of user.  The followin error pops up
![image](https://user-images.githubusercontent.com/92543518/230584448-07532159-393f-489f-8b70-ddcf7de9677d.png)

**Comment by divc13** [comment]
@Ashu3208 this is because you need to enter the Email and App password for the corresponding email for running the software locally. Instructions regarding this has been provided in the readme. We cannot enter our e-mail ids and app passwords for security reasons.

Hence, this issue can be closed.
