### ISSUE TITLE
No redirection to login page

### ISSUE THREAD

**Issue by Ashu3208** [divc13/Unified-Portal-For-Hall-Automation#12]
Instead of going to uphapythonanywhere.com , if I go to uphapythonanywhere.com/Home, it should redirect me to login page if I am not auhthenticated .

**Comment by labajyoti21** [comment]
Most likely you might not have logged out I have tried this with logged out and it is working as expected.Hare is a screenshot of that page 
![image](https://user-images.githubusercontent.com/105886949/230637701-a655ed8b-17e0-42e8-9b1e-d977478b51a7.png)

**Comment by Ashu3208** [comment]
![image](https://user-images.githubusercontent.com/92543518/230638459-3c196194-e78e-4a39-9b87-ae4a6dcae466.png)
I am talking about your Sign up page. You should provide a link to redirect the user to login page.

**Comment by divc13** [comment]
@Ashu3208 I think you have commented in the wrong issue. What @labajyoti21 said is that we wanted to throw error if someone peeps into our website without getting authenticated. The main page of our website already asks for login, hence using home link directly should give peeping error, which has been implemented. This matches our requirements for the software, and hence is not an issue.

Please close the issue if satisfied.

**Comment by divc13** [comment]
Also added link to login page on error file.
