### ISSUE TITLE
Every page title is upha

### ISSUE THREAD

**Issue by Ashu3208** [divc13/Unified-Portal-For-Hall-Automation#13]
![image](https://user-images.githubusercontent.com/92543518/230589098-60e2bf99-ba3a-4efd-b40f-c70bb016db29.png)
![image](https://user-images.githubusercontent.com/92543518/230589138-dce8105f-a9f9-4a34-8a50-bf7aacadb8e2.png)
![image](https://user-images.githubusercontent.com/92543518/230589163-2fddcaf5-6e19-46bd-a1f6-e93c80515604.png)
Every page is titled UPHA . Pages can be titled differently to distinguish

**Comment by labajyoti21** [comment]
This is intentional  that is the name of our website.
