### ISSUE TITLE
Mess Menu frontend

### ISSUE THREAD

**Issue by Ashu3208** [divc13/Unified-Portal-For-Hall-Automation#14]
![image](https://user-images.githubusercontent.com/92543518/230589434-0cd3c442-fe22-412a-b58e-dfb914233416.png)
Mess Menu are not sorted day wise. Instead they are shown in the order in which they are updated by mess manager.

**Comment by divc13** [comment]
@Ashu3208  You can check this issue has been resolved. Please close the issue if so.
