### ISSUE TITLE
No option to update bdmr

### ISSUE THREAD

**Issue by Ashu3208** [divc13/Unified-Portal-For-Hall-Automation#18]
![image](https://user-images.githubusercontent.com/92543518/230591957-8a69cad6-6bb4-4e46-b0e7-cbf9d85435d1.png)
If for the same day, we enter bdmr multiple times, then instead of having the latest value of bdmr, all the previous values gets summed up
![image](https://user-images.githubusercontent.com/92543518/230592090-80e00034-5f48-467c-979c-51ea7ef836d9.png)

**Comment by pranjalsingh4550** [comment]
I think you accidentally entered the BDMR for different days.. Please see these entries in the database on django admin:
![image](https://user-images.githubusercontent.com/96577548/230731647-ef82e2a5-b704-47bf-aa9e-f6f6cd09a842.png)
![image](https://user-images.githubusercontent.com/96577548/230731691-cc765953-cd3d-4aca-9db6-9b08bbf164ff.png)
We had checked this in the implementation phase.
