### ISSUE TITLE
No option for avergae bdmr

### ISSUE THREAD

**Issue by Ashu3208** [divc13/Unified-Portal-For-Hall-Automation#19]
![image](https://user-images.githubusercontent.com/92543518/230593117-f7a654a8-d3b4-4652-b384-02eb54d38640.png)
There is no option for mess manager to have an average bdmr for the whole month. So for updating bill, manager have to add bdmr daily.

**Comment by Kriti-Arora-08** [comment]
In mess, students like to know the daily BDMR and this is also how the BDMR is calculated. In fact, this is what BDMR means: Basic **Daily** Mess Rate. The billing system in the app works such that, each students mess bill gets updated daily and doesn't require any manual calculations by the manager at the end of month which are required to calculate average BDMR.
