### ISSUE TITLE
No limit on input size during signup

### ISSUE THREAD

**Issue by Ashu3208** [divc13/Unified-Portal-For-Hall-Automation#20]
![image](https://user-images.githubusercontent.com/92543518/230594227-c43b03c0-797a-4c63-b54d-a3262e501071.png)

No limit on Name-
dsssssssssssssssssssssssssssssssssssssssssssaweweweqwwasddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddwqeqwewqeqeqweqrqrettrtethrhfnhLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum

I have provided the above argument as name and still otp has being sent

**Comment by divc13** [comment]
@Ashu3208 This has been resolved. You can close the issue, if satisfied.

**Comment by Ashu3208** [comment]
Did u resolve this in the hosted version of your website. As same thing is still going on there

**Comment by divc13** [comment]
Yes it was updated. You cannot input more than 50 characters. Please verify and close the issue.
