### ISSUE TITLE
Canteen secy Account

### ISSUE THREAD

**Issue by Ashu3208** [divc13/Unified-Portal-For-Hall-Automation#21]
Secretaries are generally student and each student has only one cc id.  So a canteen secretary being a student will be unable to register themselves as canteen secretary.

**Comment by Jhalakk-21** [comment]
@Ashu3208 Please elaborate why we need a separate account for a canteen secy? 
There’s no mention of canteen secy anywhere in the software, all canteen related functionalities are managed by the canteen owner. Also, having a separate account for canteen secy can be a good idea for the next version, but not a bug for this one. 
Please close the issue, if satisfied.
