### ISSUE TITLE
Email id updation

### ISSUE THREAD

**Issue by Ashu3208** [divc13/Unified-Portal-For-Hall-Automation#22]
A separate single account is created for Hall manager, Canteen Secretary, Mess Manager and Sports Secretary and they all are registered with iitk email. But if Hall managers changes or leaves the institution, there is no option to update the email for new person in position.

**Comment by Jhalakk-21** [comment]
@Ashu3208 Generally in IITK, email ids are provided for the designation and not for personal use. So, if any of the above mentioned person leaves, then the email id would pass on to the next person on that specific designation, hence no need to update anything.
Please close the issue, if satisfied.
