### ISSUE TITLE
No option to request quantity

### ISSUE THREAD

**Issue by Ashu3208** [divc13/Unified-Portal-For-Hall-Automation#23]
There is no option to request the quantity of equipments
![image](https://user-images.githubusercontent.com/92543518/230596660-ea1b5ce5-3000-4f6d-90f7-0bb26b55c55b.png)

**Comment by Divyanshsingh1910** [comment]
@Ashu3208  can you please elaborate a bit on what you exactly mean by requesting quantities If you are talking about the option for the quantity of equipment then it is our formulation that one student can request only one item for a sport at a time.

**Comment by Ashu3208** [comment]
Cosider Badminton for example.  2 rackets are required for each player and it would be convenient that one can request for 2 rackets

**Comment by Divyanshsingh1910** [comment]
@Ashu3208 I understand that it will be convenient if just one person can issue for both of them, but in our formulation, both of them have to request rackets separately as we have intentionally limited **"One item per student per sport"** for even access to sports resources.
Please close this issue if satisfied
