### ISSUE TITLE
A student can book court for all time

### ISSUE THREAD

**Issue by Ashu3208** [divc13/Unified-Portal-For-Hall-Automation#25]
![image](https://user-images.githubusercontent.com/92543518/230675679-2afd6b47-4a7e-4d90-a239-54579c684594.png)
There is no check on the number of hour a court can be booked. Thus a single student can book court for the entire day

**Comment by Divyanshsingh1910** [comment]
@Ashu3208 I have limited the booking time to 3 hours now; hence,  please close this issue if satisfied.
