### ISSUE TITLE
Negative value in clear amount

### ISSUE THREAD

**Issue by Ashu3208** [divc13/Unified-Portal-For-Hall-Automation#29]
![image](https://user-images.githubusercontent.com/92543518/230678402-ff08aed0-3f14-4199-b028-4768a7641d9f.png)
![image](https://user-images.githubusercontent.com/92543518/230678430-55cbe75e-998b-4948-8332-f6b0f8ef93de.png)
Negative value is accepted in clear amount

**Comment by harshmohan21** [comment]
We have deliberately included the feature to accept negative values in our software, as it is possible that a student may purchase an item without using the software but still wants the canteen manager to add the amount to their account. In such cases, the canteen manager can use a negative value to add the amount to the student's account. Hope it clarifies your issue regarding this.

**Comment by Ashu3208** [comment]
So that can be done by specifying more clear options such as other dues instead of a negative value

**Comment by divc13** [comment]
This issue has been resolved. You can check and close the issue.
