### ISSUE TITLE
No option to see who has borrowed which equipment 

### ISSUE THREAD

**Issue by Ashu3208** [divc13/Unified-Portal-For-Hall-Automation#8]
![Issue1](https://user-images.githubusercontent.com/92543518/230579516-b6434638-12e2-4df0-b79b-7596256babb3.png)
There is no option for sport secy to see who has borrowed what equipment in the past.

**Comment by Divyanshsingh1910** [comment]
@Ashu3208 I have added a new option `Equipment Logs` at the end of Sports secy to see who has booked what item: hence please close the issue if satisfied.
