### ISSUE TITLE
No option to return to login page from registration page

### ISSUE THREAD

**Issue by Ashu3208** [divc13/Unified-Portal-For-Hall-Automation#9]
![image](https://user-images.githubusercontent.com/92543518/230581989-1d2b32a6-ae9b-4a85-95bb-6d4054105fde.png)
If somebody mistakenly clicks on new user , then they don't have the option to go to login page. They have to reload the website

**Comment by divc13** [comment]
@Ashu3208 This has been resolved. You can close the issue, if satisfied.
